### ISSUE TITLE
Improve and extend test suite

### ISSUE THREAD

**Issue by daKmoR** [hmans/three-elements#8]
I would have assume `@web/test-runner` and `@open-wc/testing` to be used for testing the web components...

however it seems there are no test 🤔

**Comment by hmans** [comment]
There will be tests. This library is a few days old. :)

Testing this is going to be interesting, and I will need to read up on the current state of the art of integration testing with WebGL. Please keep kicking my butt about this!

**Comment by hmans** [comment]
Thanks for pointing me towards `@web/test-runner` and `@open-wc/testing`. I've started adding tests to the library. What's there is still relatively simple, but it'll grow over time.

**Comment by daKmoR** [comment]
sweet -  having the setup up and running is already a big step 👍

**Comment by CodyJasonBennett** [comment]
I'm curious if there's a way to test interactions in WebGL and WebXR here.

**Comment by hmans** [comment]
> I'm curious if there's a way to test interactions in WebGL and WebXR here.

As far as I understand, testing that kind of stuff is really hard -- and mostly involves taking render snapshots and comparing them to catch regressions. It's definitely something I want to look deeper into.

**Comment by CodyJasonBennett** [comment]
It's a longshot, but I think we can focus on elements' lifecycles and DOM events for now.

**Comment by hmans** [comment]
Further work has been done here, especially in terms of moving things away from that big, almost-monolithic .html test, to smaller, case-specific .ts tests.

**Comment by hmans** [comment]
We now have a pretty solid test harness and are continuously adding new tests for added or changed features. I'm closing this ticket.  Thanks for kicking my butt about this!
